# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 472ed6dd6c63fcd8cb62ecb30f45237870ef4db26dcb8e711cef0474810de4bb8337345a855d4075489ae3554548f725774fd2b0bfba15400540e5e2a10d3b85

test:
  secret_key_base: b122ddb2dbe06591183fa964df59bf056a7d5730ca7ec86c56788a0d60eb66aac2bba3a4b8e43d6be21163470d62c5f925916e5f8efeda0e1db350196cffe997

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
